---
- name: localhost-tasks
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: calculate-sha256-checksum
    stat:
      path: "{{ item }}"
      checksum_algorithm: sha256
      get_checksum: yes
    register: checksums
    with_fileglob: scripts/*.py
    no_log: true
  - name: show-checksum
    debug:
      msg: "FILE: {{ item.item }}, CHECKSUM: {{ item.stat.checksum  }}"
    with_items: "{{ checksums.results }}"

- name: network-device-tasks
  hosts: lab-leaf
  connection: local
  gather_facts: no
  tasks:
  - name: check_netconf_connection
    tags: check_netconf_connection
    wait_for: host="{{ inventory_hostname }}" port=830  timeout=5
  - name: upload-scripts-to-device
    junos_scp:
      provider:
        host: "{{ inventory_hostname }}"
        username: admin
        password: "{{ ansible_ssh_pass }}"
      src: "{{ item.item }}"
      dest: /var/db/scripts/op
    with_items: "{{ hostvars['localhost']['checksums'].results }}"
    no_log: true
  - name: add-scripts-to-configuration
    junos_config:
      provider:
        host: "{{ inventory_hostname }}"
        username: admin
        password: "{{ ansible_ssh_pass }}"
      lines:
      - set system scripts op file "{{ item.item.split('/')[-1] }}" checksum sha-256 "{{ item.stat.checksum }}"
    with_items: "{{ hostvars['localhost']['checksums'].results }}"
    no_log: true
