---
interfaces:
- name: ge-0/0/0
  address: 192.168.5.1/24
  description: WAN
- name: ge-0/0/1
  address: 192.168.6.1/24
  description: LAN1
- name: ge-0/0/2
  address: 192.168.7.1/24
  description: LAN2
